name: Build and Push

on:
  push:
    branches:
      - main
      - docker-build
  workflow_dispatch:

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{secrets.GH_USERNAME}}
          password: ${{secrets.GH_TOKEN}}

      - name: "Build Inventory Image"
        run: |
          docker build --tag ghcr.io/campbel/tiny-tunnel:latest .
          docker push ghcr.io/campbel/tiny-tunnel:latest
