name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Setup go"
        uses: actions/setup-go@v2
        with:
          go-version: '^1.22'

      - name: Test
        uses: robherley/go-test-action@v0.1.0
